Refactor OpenJDK installation (#339)

diff --git a/bin/java b/bin/java
--- a/bin/java
+++ b/bin/java
@@ -10,14 +10,6 @@ JVM_COMMON_BUILDPACK_DIR="${JVM_COMMON_BUILDPACK_DIR:-$(cd "$(dirname "${BASH_SO
 # not be set. It should always default to the latest stack.
 STACK="${STACK:-"heroku-24"}"
 
-if [ "${STACK}" == "heroku-24" ]; then
-	# This should always be the latest OpenJDK LTS major version
-	# Next LTS will be OpenJDK 25 with a planned release date of 2025-09-16
-	DEFAULT_JDK_VERSION="21"
-else
-	DEFAULT_JDK_VERSION="1.8"
-fi
-
 # shellcheck source=lib/output.sh
 source "${JVM_COMMON_BUILDPACK_DIR}/lib/output.sh"
 # shellcheck source=lib/inventory.sh
@@ -26,140 +18,134 @@ source "${JVM_COMMON_BUILDPACK_DIR}/lib/inventory.sh"
 source "${JVM_COMMON_BUILDPACK_DIR}/lib/java_properties.sh"
 
 install_java_with_overlay() {
-	local buildDir="${1}"
+	local build_dir="${1}"
+	local openjdk_install_dir="${build_dir}/.jdk"
 
-	if [ ! -f "${buildDir}/.jdk/bin/java" ]; then
-		if [ -z "$(java_properties::get "${buildDir}/system.properties" "java.runtime.version")" ]; then
-			if [ "${STACK}" == "heroku-24" ]; then
-				output::warning <<-EOF
-					WARNING: No OpenJDK version specified
+	if [ -d "${openjdk_install_dir}" ]; then
+		_conditional_meta_set "openjdk_version" "provided"
+		_conditional_meta_set "openjdk_distribution" "provided"
 
-					Your application does not explicitly specify an OpenJDK
-					version. The latest long-term support (LTS) version will be
-					installed. This currently is OpenJDK ${DEFAULT_JDK_VERSION}.
-
-					This default version will change when a new LTS version is
-					released. Your application might fail to build with the new
-					version. We recommend explicitly setting the required OpenJDK
-					version for your application.
-
-					To set the OpenJDK version, add or edit the system.properties
-					file in the root directory of your application to contain:
-
-					java.runtime.version = ${DEFAULT_JDK_VERSION}
-				EOF
-			else
-				output::warning <<-EOF
-					WARNING: No OpenJDK version specified
-
-					Your application does not explicitly specify an OpenJDK
-					version. OpenJDK ${DEFAULT_JDK_VERSION} will be installed.
-
-					This default version will change at some point. Your
-					application might fail to build with the new version. We
-					recommend explicitly setting the required OpenJDK version for
-					your application.
-
-					To set the OpenJDK version, add or edit the system.properties
-					file in the root directory of your application to contain:
-
-					java.runtime.version = ${DEFAULT_JDK_VERSION}
-				EOF
-			fi
-		fi
-
-		local jdkVersion
-		jdkVersion="$(java_properties::get "${buildDir}/system.properties" "java.runtime.version")"
-		jdkVersion="${jdkVersion:-${DEFAULT_JDK_VERSION}}"
-
-		local jdkUrl
-		jdkUrl=$(_get_jdk_url_with_default "${jdkVersion}")
-
-		_jvm_mcount "version.${jdkVersion}"
-		if [[ "$jdkVersion" == *openjdk* ]]; then
-			output::step "Installing Heroku OpenJDK $(_get_openjdk_version "${jdkVersion}")"
-			_jvm_mcount "vendor.openjdk"
-		elif [[ "$jdkVersion" == *heroku* ]]; then
-			output::step "Installing Heroku OpenJDK $(_get_heroku_version "${jdkVersion}")"
-			_jvm_mcount "vendor.openjdk"
-		elif [[ "$jdkVersion" == *zulu* ]]; then
-			output::step "Installing Azul Zulu OpenJDK $(_get_zulu_version "${jdkVersion}")"
-			_jvm_mcount "vendor.zulu"
-		else
-			output::step "Installing OpenJDK ${jdkVersion}"
-			_jvm_mcount "vendor.default"
-		fi
-
-		install_java "${buildDir}" "${jdkVersion}" "${jdkUrl}"
-		install_jdk_overlay "${buildDir}/.jdk" "${buildDir}"
-
-	else
 		output::step "Using provided JDK"
-		_jvm_mcount "vendor.provided"
+
+		# This will also skip installation of `.profile.d` scripts and other files. This is intentional to preserve
+		# historical behaviour. Since the provided JDK feature will be removed at some later point, there are no plans
+		# to change this behaviour.
+		return 0
 	fi
-}
 
-install_java() {
-	local build_dir=${1}
-	local jdkVersion="${2}"
-	local jdkUrl=${3:-$(_get_jdk_url_with_default "${jdkVersion}")}
+	local openjdk_version_selector
+	openjdk_version_selector="$(java_properties::get "${build_dir}/system.properties" "java.runtime.version")"
+	_conditional_meta_set "openjdk_version_selector" "${openjdk_version_selector}"
 
-	local jdkDir="${build_dir}"/.jdk
-	local javaExe="${jdkDir}/bin/java"
-	mkdir -p "${jdkDir}"
+	if [ -z "${openjdk_version_selector}" ]; then
+		if [ "${STACK}" == "heroku-24" ]; then
+			# This should always be the latest OpenJDK LTS major version
+			# Next LTS will be OpenJDK 25 with a planned release date of 2025-09-16
+			openjdk_version_selector="21"
 
-	if [ ! -f "${javaExe}" ] || is_java_version_change "${jdkDir}" "${jdkVersion}"; then
-		rm -rf "${jdkDir}"
-		mkdir -p "${jdkDir}"
+			output::warning <<-EOF
+				WARNING: No OpenJDK version specified
 
-		if [ "$(curl_with_defaults --retry 3 --silent --head -w "%{http_code}" -L "${jdkUrl}" -o /dev/null)" != "200" ]; then
-			output::error <<-EOF
-				ERROR: Unsupported Java version: ${jdkVersion}
+				Your application does not explicitly specify an OpenJDK
+				version. The latest long-term support (LTS) version will be
+				installed. This currently is OpenJDK ${openjdk_version_selector}.
 
-				Please check your system.properties file to ensure the java.runtime.version
-				is among the list of supported version on the Dev Center:
-				https://devcenter.heroku.com/articles/java-support#supported-java-versions
-				You can also remove the system.properties from your repo to install
-				the default ${DEFAULT_JDK_VERSION} version.
-				If you continue to have trouble, you can open a support ticket here:
-				https://help.heroku.com
+				This default version will change when a new LTS version is
+				released. Your application might fail to build with the new
+				version. We recommend explicitly setting the required OpenJDK
+				version for your application.
 
-				Thanks,
-				Heroku
+				To set the OpenJDK version, add or edit the system.properties
+				file in the root directory of your application to contain:
+
+				java.runtime.version = ${openjdk_version_selector}
 			EOF
+		else
+			openjdk_version_selector="1.8"
 
-			return 1
-		fi
+			output::warning <<-EOF
+				WARNING: No OpenJDK version specified
 
-		# Download and extract OpenJDK distribution
-		local jdk_tarball="/tmp/jdk.tgz"
-		curl_with_defaults --retry 3 --silent --show-error --location "${jdkUrl}" --output "${jdk_tarball}"
-		tar -pxzf "${jdk_tarball}" -C "${jdkDir}"
-		rm "${jdk_tarball}"
+				Your application does not explicitly specify an OpenJDK
+				version. OpenJDK ${openjdk_version_selector} will be installed.
 
-		# Link base image Java keystore into the installed OpenJDK distribution, replacing the bundled
-		# certificates. Linking ensures that when the application image is rebased, the certificates are
-		# updated for JVM applications, even though the OpenJDK distribution itself doesn't change.
-		if [ -f "${jdkDir}/jre/lib/security/cacerts" ] && [ -f "/etc/ssl/certs/java/cacerts" ]; then
-			mv "${jdkDir}/jre/lib/security/cacerts" "${jdkDir}/jre/lib/security/cacerts.old"
-			ln -s "/etc/ssl/certs/java/cacerts" "${jdkDir}/jre/lib/security/cacerts"
-		elif [ -f "${jdkDir}/lib/security/cacerts" ] && [ -f "/etc/ssl/certs/java/cacerts" ]; then
-			mv "${jdkDir}/lib/security/cacerts" "${jdkDir}/lib/security/cacerts.old"
-			ln -s "/etc/ssl/certs/java/cacerts" "${jdkDir}/lib/security/cacerts"
-		fi
+				This default version will change at some point. Your
+				application might fail to build with the new version. We
+				recommend explicitly setting the required OpenJDK version for
+				your application.
 
-		echo "${jdkVersion}" >"${jdkDir}/version"
-		if [ ! -f "${javaExe}" ]; then
-			output::error <<-EOF
-				Unable to retrieve the JDK.
+				To set the OpenJDK version, add or edit the system.properties
+				file in the root directory of your application to contain:
+
+				java.runtime.version = ${openjdk_version_selector}
 			EOF
-
-			return 1
 		fi
 	fi
 
-	export JAVA_HOME=${jdkDir}
-	export PATH="${jdkDir}/bin:${PATH}"
+	if ! openjdk_json=$(inventory::query "${openjdk_version_selector}" "${STACK}"); then
+		output::error <<-EOF
+			ERROR: Unsupported Java version: ${openjdk_version_selector}
+
+			Please check your system.properties file to ensure the java.runtime.version
+			is among the list of supported version on the Dev Center:
+			https://devcenter.heroku.com/articles/java-support#supported-java-versions
+
+			If you continue to have trouble, you can open a support ticket here:
+			https://help.heroku.com
+
+			Thanks,
+			Heroku
+		EOF
+
+		return 1
+	fi
+
+	local openjdk_version
+	openjdk_version=$(jq -r '.version' <<<"${openjdk_json}")
+
+	local openjdk_distribution
+	openjdk_distribution=$(jq -r '.metadata.distribution' <<<"${openjdk_json}")
+
+	local openjdk_distribution_name
+	case "${openjdk_distribution}" in
+	"zulu") openjdk_distribution_name="Azul Zulu OpenJDK" ;;
+	"heroku") openjdk_distribution_name="Heroku OpenJDK" ;;
+	*) openjdk_distribution_name="OpenJDK" ;;
+	esac
+
+	local openjdk_url
+	openjdk_url=$(jq -r '.url' <<<"${openjdk_json}")
+
+	_conditional_meta_set "openjdk_version" "${openjdk_version}"
+	_conditional_meta_set "openjdk_distribution" "${openjdk_distribution}"
+
+	output::step "Installing ${openjdk_distribution_name} ${openjdk_version}"
+
+	rm -rf "${openjdk_install_dir}"
+	mkdir "${openjdk_install_dir}"
+
+	# Download and extract OpenJDK distribution
+	local openjdk_install_start_time
+	openjdk_install_start_time=$(nowms)
+
+	local jdk_tarball="/tmp/jdk.tgz"
+	curl_with_defaults --retry 3 --silent --show-error --location "${openjdk_url}" --output "${jdk_tarball}"
+	tar -pxzf "${jdk_tarball}" -C "${openjdk_install_dir}"
+	rm "${jdk_tarball}"
+
+	_conditional_meta_time "openjdk_install_duration" "${openjdk_install_start_time}"
+
+	# Link base image Java keystore into the installed OpenJDK distribution, replacing the bundled
+	# certificates. Linking ensures that when the application image is rebased, the certificates are
+	# updated for JVM applications, even though the OpenJDK distribution itself doesn't change.
+	if [[ -f "/etc/ssl/certs/java/cacerts" ]]; then
+		for path in "${openjdk_install_dir}/jre/lib/security/cacerts" "${openjdk_install_dir}/lib/security/cacerts"; do
+			if [[ -f "${path}" ]]; then
+				mv "${path}" "${path}.old"
+				ln -s "/etc/ssl/certs/java/cacerts" "${path}"
+			fi
+		done
+	fi
 
 	# Download Heroku JVM metrics agent JAR
 	mkdir -p "${build_dir}/.heroku/bin"
@@ -181,100 +167,49 @@ install_java() {
 	# Write export script for subsequent buildpacks to ensure they can use the installed OpenJDK.
 	# See: https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks
 	cat <<-EOF >"${JVM_COMMON_BUILDPACK_DIR}/export"
-		export JAVA_HOME=${JAVA_HOME}
+		export JAVA_HOME=${openjdk_install_dir}
 		export PATH=\$JAVA_HOME/bin:\$PATH
 		export LD_LIBRARY_PATH="\$JAVA_HOME/jre/lib/amd64/server:\${LD_LIBRARY_PATH:-}"
 	EOF
 
+	# Source the export script manually here to ensure that other buildpacks that use this buildpack as a library
+	# also have the correct environment variables available.
+	# shellcheck source=/dev/null
+	source "${JVM_COMMON_BUILDPACK_DIR}/export"
+
 	# Install an extension into the OpenJDK distribution extension folder should is exist. This will only
 	# be the case for Java 8 as this OpenJDK feature was deprecated in 8u40.
 	# This JAR file sets `sslmode=require` for the postgres drivers.
-	local extDir="${JAVA_HOME}/jre/lib/ext"
-	if [[ -d "${extDir}" ]] && [[ -z "${SKIP_PGCONFIG_INSTALL:-}" ]] && [[ "${CI:-}" != "true" ]]; then
-		curl_with_defaults --retry 3 -s -L "https://lang-jvm.s3.us-east-1.amazonaws.com/pgconfig.jar" -o "${extDir}/pgconfig.jar"
+	local openjdk_jre_ext_dir="${openjdk_install_dir}/jre/lib/ext"
+	if [[ -d "${openjdk_jre_ext_dir}" ]] && [[ -z "${SKIP_PGCONFIG_INSTALL:-}" ]] && [[ "${CI:-}" != "true" ]]; then
+		curl_with_defaults --retry 3 -s -L "https://lang-jvm.s3.us-east-1.amazonaws.com/pgconfig.jar" -o "${openjdk_jre_ext_dir}/pgconfig.jar"
 	fi
-}
 
-is_java_version_change() {
-	jdkDir=$1
-	jdkVersion=${2:-${DEFAULT_JDK_VERSION}}
-	if [ ! -d "${jdkDir}" ]; then
-		echo "Invalid JDK directory."
-		return 1
-	fi
-	test -f "${jdkDir}/version" && [ "$(cat "${jdkDir}/version")" != "${jdkVersion}" ]
-}
+	# Apply the JDK overlay to the installed OpenJDK
+	if [[ -d "${build_dir}/.jdk-overlay/" ]]; then
+		_conditional_meta_set "app_has_jdk_overlay" "true"
 
-# Legacy functions for backwards compatability
-detect_java_version() {
-	local jdkVersion
-	jdkVersion="$(java_properties::get "${1}/system.properties" "java.runtime.version")"
-	jdkVersion="${jdkVersion:${DEFAULT_JDK_VERSION}}"
+		# Some symlinks need to be removed before the final cp command so that it doesn't fail.
+		for path in jre/lib/security/cacerts lib/security/cacerts; do
+			if [[ -f "${build_dir}/.jdk-overlay/${path}" ]] && [[ -f "${openjdk_install_dir}/${path}" ]]; then
+				rm "${openjdk_install_dir}/${path}"
+			fi
+		done
 
-	echo "${jdkVersion}"
-}
-
-jdk_overlay() {
-	local buildDir="${1}"
-	install_jdk_overlay "${buildDir}/.jdk" "${buildDir}"
-}
-
-# Internal functions
-
-install_jdk_overlay() {
-	local jdkDir="${1:?}"
-	local appDir="${2:?}"
-	local cacertPath="lib/security/cacerts"
-	shopt -s dotglob
-
-	if [ -d "${jdkDir}" ] && [ -d "${appDir}/.jdk-overlay" ]; then
-		# delete the symlink because a cp will error
-		if [ -f "${appDir}/.jdk-overlay/jre/${cacertPath}" ] && [ -f "${jdkDir}/jre/${cacertPath}" ]; then
-			rm "${jdkDir}/jre/${cacertPath}"
-		elif [ -f "${appDir}/.jdk-overlay/${cacertPath}" ] && [ -f "${jdkDir}/${cacertPath}" ]; then
-			rm "${jdkDir}/${cacertPath}"
-		fi
-
-		cp -r "${appDir}/.jdk-overlay/"* "${jdkDir}"
-	fi
-}
-
-# This function implements a legacy behavior in which the JDK_URL_1_8 or similar config var
-# could be used to override the URL to the JDK binary for a specific version. It's
-# not supported in the v3 implementation of the buildpack.
-_get_jdk_url_with_default() {
-	local jdkVersion="${1:?}"
-	if [ -n "${JDK_URL_1_7:-}" ] && { [ "$(expr "${jdkVersion}" : '^1.7')" != 0 ] || [ "$(expr "${jdkVersion}" : '^7')" != 0 ]; }; then
-		echo "$JDK_URL_1_7"
-	elif [ -n "${JDK_URL_1_8:-}" ] && { [ "$(expr "${jdkVersion}" : '^1.8')" != 0 ] || [ "$(expr "${jdkVersion}" : '^8')" != 0 ]; }; then
-		echo "$JDK_URL_1_8"
-	elif [ -n "${JDK_URL_1_9:-}" ] && { [ "$(expr "${jdkVersion}" : '^1.9')" != 0 ] || [ "$(expr "${jdkVersion}" : '^9')" != 0 ]; }; then
-		echo "$JDK_URL_1_9"
-	elif [ -n "${JDK_URL_10:-}" ] && [ "$(expr "${jdkVersion}" : '^10')" != 0 ]; then
-		echo "$JDK_URL_10"
-	elif [ -n "${JDK_URL_11:-}" ] && [ "$(expr "${jdkVersion}" : '^11')" != 0 ]; then
-		echo "$JDK_URL_11"
-	elif [ -n "${JDK_URL_12:-}" ] && [ "$(expr "${jdkVersion}" : '^12')" != 0 ]; then
-		echo "$JDK_URL_12"
-	elif [ -n "${JDK_URL_13:-}" ] && [ "$(expr "${jdkVersion}" : '^13')" != 0 ]; then
-		echo "$JDK_URL_13"
+		cp -r "${build_dir}/.jdk-overlay/"* "${openjdk_install_dir}"
 	else
-		inventory::query "${jdkVersion}" "${STACK}" | jq -r ".url"
+		_conditional_meta_set "app_has_jdk_overlay" "false"
 	fi
 }
 
-_get_zulu_version() {
-	echo "${1//zulu-/}"
+# This file will be included by other buildpacks that might not have or might not have set up
+# the metadata file for reporting. To ensure we don't break those buildpacks but still be able to
+# set metadata about OpenJDK, we have wrapper functions that check for a proper setup first.
+
+_conditional_meta_set() {
+	if type -t meta_set >/dev/null; then meta_set "${1}" "${2}"; fi
 }
 
-_get_openjdk_version() {
-	echo "${1//openjdk-/}"
-}
-
-_get_heroku_version() {
-	echo "${1//heroku-/}"
-}
-
-_jvm_mcount() {
-	if type -t mcount >/dev/null; then mcount "jvm.${1}"; fi
+_conditional_meta_time() {
+	if type -t meta_time >/dev/null; then meta_time "${1}" "${2}"; fi
 }
