WIP

diff --git a/bin/java b/bin/java
--- a/bin/java
+++ b/bin/java
@@ -34,21 +34,22 @@ install_java_with_overlay() {
 		return 0
 	fi
 
-	local version_selection_string
-	version_selection_string="$(java_properties::get "${build_dir}/system.properties" "java.runtime.version")"
+	local openjdk_version_selector
+	openjdk_version_selector="$(java_properties::get "${build_dir}/system.properties" "java.runtime.version")"
+	_conditional_meta_set "openjdk_version_selector" "${openjdk_version_selector}"
 
-	if [ -z "${version_selection_string}" ]; then
+	if [ -z "${openjdk_version_selector}" ]; then
 		if [ "${STACK}" == "heroku-24" ]; then
 			# This should always be the latest OpenJDK LTS major version
 			# Next LTS will be OpenJDK 25 with a planned release date of 2025-09-16
-			version_selection_string="21"
+			openjdk_version_selector="21"
 
 			output::warning <<-EOF
 				WARNING: No OpenJDK version specified
 
 				Your application does not explicitly specify an OpenJDK
 				version. The latest long-term support (LTS) version will be
-				installed. This currently is OpenJDK ${version_selection_string}.
+				installed. This currently is OpenJDK ${openjdk_version_selector}.
 
 				This default version will change when a new LTS version is
 				released. Your application might fail to build with the new
@@ -58,16 +59,16 @@ install_java_with_overlay() {
 				To set the OpenJDK version, add or edit the system.properties
 				file in the root directory of your application to contain:
 
-				java.runtime.version = ${version_selection_string}
+				java.runtime.version = ${openjdk_version_selector}
 			EOF
 		else
-			version_selection_string="1.8"
+			openjdk_version_selector="1.8"
 
 			output::warning <<-EOF
 				WARNING: No OpenJDK version specified
 
 				Your application does not explicitly specify an OpenJDK
-				version. OpenJDK ${version_selection_string} will be installed.
+				version. OpenJDK ${openjdk_version_selector} will be installed.
 
 				This default version will change at some point. Your
 				application might fail to build with the new version. We
@@ -77,14 +78,14 @@ install_java_with_overlay() {
 				To set the OpenJDK version, add or edit the system.properties
 				file in the root directory of your application to contain:
 
-				java.runtime.version = ${version_selection_string}
+				java.runtime.version = ${openjdk_version_selector}
 			EOF
 		fi
 	fi
 
-	if ! openjdk_json=$(inventory::query "${version_selection_string}" "${STACK}"); then
+	if ! openjdk_json=$(inventory::query "${openjdk_version_selector}" "${STACK}"); then
 		output::error <<-EOF
-			ERROR: Unsupported Java version: ${version_selection_string}
+			ERROR: Unsupported Java version: ${openjdk_version_selector}
 
 			Please check your system.properties file to ensure the java.runtime.version
 			is among the list of supported version on the Dev Center:
@@ -184,35 +185,22 @@ install_java_with_overlay() {
 		curl_with_defaults --retry 3 -s -L "https://lang-jvm.s3.us-east-1.amazonaws.com/pgconfig.jar" -o "${extDir}/pgconfig.jar"
 	fi
 
-	local cacertPath="lib/security/cacerts"
+	# Apply the JDK overlay to the installed OpenJDK
+	if [[ -d "${build_dir}/.jdk-overlay/" ]]; then
+		_conditional_meta_set "app_contains_jdk_overlay" "true"
 
-	if [[ -d "${build_dir}/.jdk-overlay" ]]; then
-		# delete the symlink because a cp will error
-		if [ -f "${build_dir}/.jdk-overlay/jre/${cacertPath}" ] && [ -f "${openjdk_install_dir}/jre/${cacertPath}" ]; then
-			rm "${openjdk_install_dir}/jre/${cacertPath}"
-		elif [ -f "${build_dir}/.jdk-overlay/${cacertPath}" ] && [ -f "${openjdk_install_dir}/${cacertPath}" ]; then
-			rm "${openjdk_install_dir}/${cacertPath}"
-		fi
+		# Some symlinks need to be removed before the final cp command so that it doesn't fail.
+		for path in jre/lib/security/cacerts lib/security/cacerts; do
+			if [[ -f "${build_dir}/.jdk-overlay/${path}" ]] && [[ -f "${openjdk_install_dir}/${path}" ]]; then
+				rm "${openjdk_install_dir}/${path}"
+			fi
+		done
 
 		cp -r "${build_dir}/.jdk-overlay/"* "${openjdk_install_dir}"
+	else
+		_conditional_meta_set "app_contains_jdk_overlay" "false"
 	fi
 }
-
-# Legacy functions for backwards compatability
-detect_java_version() {
-	local jdkVersion
-	jdkVersion="$(java_properties::get "${1}/system.properties" "java.runtime.version")"
-	jdkVersion="${jdkVersion:${DEFAULT_VERSION_SELECTION_STRING}}"
-
-	echo "${jdkVersion}"
-}
-
-jdk_overlay() {
-	local buildDir="${1}"
-	install_jdk_overlay "${buildDir}/.jdk" "${buildDir}"
-}
-
-# Internal functions
 
 # This file will be included by other buildpacks that might not have or might not have set up
 # the metadata file for reporting. To ensure we don't break those buildpacks but still be able to
