revised fail conditions

diff --git a/bin/util b/bin/util
--- a/bin/util
+++ b/bin/util
@@ -4,6 +4,14 @@ error() {
   echo
   echo " !     ERROR: $*" | indent no_first_line_indent
   echo
+  exit 1
+}
+
+error_return() {
+  echo
+  echo " !     ERROR: $*" | indent no_first_line_indent
+  echo
+  return 1
 }
 
 warning() {
