Add inventory.json validation in CI (#358)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -82,3 +82,49 @@ jobs:
         run: make run
       #- name: Run buildpack using an app fixture that's expected to fail
       #  run: make run FIXTURE=spec/fixtures/failing/
+
+  validate-inventory:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Determine if inventory.json changed
+        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
+        id: changed-files
+        with:
+          files: inventory.json
+      - name: Validate inventory.json contents
+        if: steps.changed-files.outputs.any_changed == 'true'
+        run: |
+          set -euo pipefail
+
+          artifacts=$(cat inventory.json | jq -c -r '.artifacts[]')
+
+          for artifact in $artifacts; do
+            url=$(echo "${artifact}" | jq -r '.url')
+
+            # This script assumes the usage of SHA256 as the digest as we currently only use SHA256
+            # in JVM inventory files. Should this ever change, this script will fail with a checksum
+            # error, but will not let unknown digests pass silently. This makes it a safe assumption and
+            # simplifies the script.
+            sha256_checksum=$(echo "${artifact}" | jq -r '.checksum[7:]')
+
+            echo -n "${url}... "
+
+            temp_file=$(mktemp)
+
+            if ! curl --silent --fail -o "${temp_file}" "${url}"; then
+              echo "DOWNLOAD ERROR"
+              exit 1
+            fi
+
+            actual_sha256_checksum=$(shasum -a256 "${temp_file}" | cut -d' ' -f1)
+            if [[ "${actual_sha256_checksum}" == "${sha256_checksum}" ]]; then
+              echo "OK"
+            else
+              echo "CHECKSUM ERROR"
+              exit 1
+            fi
+
+            rm "${temp_file}"
+          done
